<!DOCTYPE html>
<html>
    <head>
        <link rel=stylesheet href='/styles/global.css' />
        <script src="/libs/jquery.min.js"></script>
        <script src="/scripts/global.js"></script>
    </head>
    <body>
        <header>

        </header>

        <div id="content">
            <a href="#" id="register">Incluir novo</a>
            <div id="form">
                <fieldset>
                    <legend>Cadastro</legend>
                    <p><label for="nome">Nome</label>
                    <input type="text" name="nome" /></p>
                    <p><label for="name">Username:</label>
                    <input type="text" name="name" id="name" /><p />
                    <p>
                    <label for="mail">E-mail:</label>
                    <input type="text" name="mail" id="mail" /></p>
                    <p>
                    <label for="address">Address:</label>
                    <input type="text" name="address" id="address" size="40" /><p />
                    <p><button id="send">cadastrar</button></p>
                </fieldset>
            </div>
            <table class="clients">
                <thead>
                    <tr>
                        <th>Nome</th><th>Cidade</th>
                    </tr>
                </thead>
                <tbody>
                    <?php foreach ($response as $item): ?>
                    <tr class="line">
                        <td><?=$item['firstname'] . " " . $item['lastname']?></td> 
                        <td><?=$item['city'] . "-" . $item['uf']?></td>
                    </tr>
                    <?php endforeach; ?>
                </tbody>
            </table>
        </div>
    </body>
</html>
