<!DOCTYPE html>
<html>
    <head>
        <link rel=stylesheet href='/styles/global.css' />
        <script src="/scripts/global.js"></script>
    </head>
    <body>
        <header>

        </header>

        <div id="content">
            <table class="clients">
                <thead>
                    <tr>
                        <th>Nome</th><th>Cidade</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="line">
                        <td>Marcelo Oliveira</td> 
                        <td>São Bernardo do Campo</td>
                    </tr>

                    <tr class="line">
                        <td>Danúbio Soares</td>
                        <td>São Bernardo do Campo</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </body>
</html>
